#' CONFIG
#' @export CONFIG
CONFIG <- new.env(parent = emptyenv())
CONFIG$VALID_FYLKE <- c(1:12,14:15,50,18:20)
CONFIG$WEEKS_UNRELIABLE <- 3
CONFIG$HISTORICAL_ANALYSES <- seq(0,4*52*7,by=7)
#CONFIG$HISTORICAL_DELAY_VERSIONS <- c("original","2017-12","richard")
CONFIG$HISTORICAL_DELAY_VERSIONS <- c("original","2017-12")

